class Cities:
    def __init__(self):
        self.cities = {
            'Bergamo e provincia': '📍 Bergamo: Gruppo Sermig Bonate Sopra tel. 3346568303 '
                                   '\n\n📍 Curno: via Enrico Fermi 48, '
                                   'Associazione Zlaghoda tel. +3925671788 (dalle 7:30 alle 22:00)',
            'Bologna': '📍 Bologna: via Ermete Zacconi 3/A Michela tel. 3270575847 '
                       '            \n\n📍 Bologna: Piazza Spadolini 3 GRAF '
                       '(tutti i giorni dalle 17 alle 20)',
            'Brescia e provincia': '📍 Brescia: via Fratelli Ugoni 11 \n\n📍 Brescia: via Moretto 23B Agenzia viaggi '
                                   '(tutti i giorni 10:00-13:00, 15:00-18:00)'
                                   '\n\n📍 Brescia: via Moretto 24, Chiesa S.orsola'
                                   ' merc, giov, ven, sab 14:00-16:00'
                                   '\n\n📍 Folzano: via Cascina Pontevico 27 tutti i giorni '
                                   '10:00-11:30'
                                   '\n\nLa persona di riferimento: Oksana (chiamare prima per capire cosa serve '
                                   'di più) 3289572229, 3894448443',
            'Como e provincia': '📍 Albate: via Sant’Antonino 47 Chiesa di Sant Antonio\n\n📍 Lomazzo: Biblioteca, '
                                'ingresso via ''Manzoni martedì-sabato dalle 17 alle 19, Valentina 3316498726'
                                '\n\n📍 Montano Lucino: via Adda 4a''catena MixMarket 9:00-20:00'
                                '\n\n📍 Como: Via Armando Diaz, '
                                '125 Chiesa di San Donnino domenica '
                                '12-15 ',
            'Genova e provinicia': '📍 Genova: Piazza Brignole 10 Mix Markt\n\n📍 Genova: '
                                   'Piazza Vittorio Veneto 74 Mix Markt\n\n'
                                   '📍 Genova: parrocchia Gesù ''Adolescente, via Semeria 38 Associazione Amici '
                                   'del Sermig, sabato 19 marzo dalle 18 alle 19'
                                   '\n\n''📍 Genova: via di Canneto Il '
                                   'Curto 10/R negozio Angolo dell\'est (chiamare prima per capire cosa serve di più)'
                                   'tel. 0104711057'
                                   '\n\n📍 Genova: Piazza Santo Stefano, 2 Chiesa di Santo Stefano '
                                   'tutti i giorni dalle 10:00 alle 19:00'
                                   '\n\n📍 Chiavari: via Entella 109 Chiesa delle Clarisse - Volodymyr 3270575847',
            'Lecco': '📍 Lecco: via Lamarmora, 24 Officine Ravasio, l\'associazione ‘Cassago chiama Chernobyl’',
            'Milano e provincia': '📍 Milano: Via Ludovico di Breme, 11 Consolato Generale d\'Ucraina, '
                                  'tutti i giorni 09:00 - 21:00'
                                  '\n\n📍 Milano: viale F. Testi, 190 Oratorio San Giovanni Battista alla '
                                  'Bicocca - Luciano: 335389767'
                                  '- Domenica: 3339019003'
                                  '\n\n📍 Milano / Cermenate: via Meda 50, '
                                  'Parrocchia SS. Giacomo e Giovanni'
                                  '\n\n📍 Milano: via Roberto Lepetit, 31 Catena negozi Mix Market, tel +39 338 2857446'
                                  '\n\n📍 Milano / Affori: via Brusuglio, 73 Organizzazione “UCRAINA PIU’” - Iryna: 3391135816 - '
                                  'Liudmila: 3299389452 (corridoio verde tramite l’Ambasciata)'
                                  '\n\n📍 Milano / Gratosoglio: via '
                                  'Costantino Baroni 228 Comunità Oklahoma Onlus tutti i giorni'
                                  ' 8:00-23:00\n\n📍 Milano / Solari:'
                                  ' Via Giuseppe Dezza, 50 Bibliotheco (tutti i pomeriggi dalle 15.30 alle 19.00)'
                                  '\n\n📍 Milano / '
                                  'Porta Romana: Viale Sabotino 13 Dottoressa Cristina Campanini, martedì e giovedì pomeriggio '
                                  '15.00/17.30'
                                  '\n\n📍 Milano: via Ludovico di Breme 11 Ihor, +39 388 14 71 700 Tetiana, +39 320 02 82 463,'
                                  'Tetiana, +39 388 11 54 567, Lesya, +39 329 27 27 803'
                                  '\n\n📍  Milano: via Boccea 478, Basilica'
                                  ' di Santa Sofia, tel. 06 4423 0134'
                                  '\n\n📍 Milano: Piazza della Madonna dei Monti, 3 tel. 06 481 8381'
                                  '\n\n📍 Bareggio: Associazione “Rinascita in Ucraina” Svitlana: 3208004803, Nadia: 3271628865'
                                  '\n\n📍 '
                                  'Briosco: via Enrico fermi, 13 Irina +39 333 9342115'
                                  '\n\n📍 Cologno Monzese: via Rossini 39'
                                  'Elena 3899460396'
                                  '\n\n📍 Gallarate: Vicolo del Gambero, 7 LA BANCA DEL TEMPO Lunedì 16:00 -18:00'
                                  'Sabato 10:00 -12:00 -15:00-18:00, Domenica 16:00 -18:00,Nancy Perazzolo, Giorgia Ghochetta, '
                                  'Nicol Alejandra Lovazzano, Marta, +39 329 62 86 063, Valentyna, +39 347 61 28 360, Mariia,'
                                  ' +39 329 48 29 113'
                                  '\n\n📍 Muggiò: via Quadrio 10 Chiesa di Santa Maria Regina (oratorio)'
                                  '3209737122'
                                  '\n\n📍 Seregno: via Enrico Fermi, 41 Tania +39 340 6623907'
                                  '\n\n📍 Settimo Milanese:'
                                  ' via Reiss Romoli spazio polifunzionale Castelletto '
                                  '\n\n📍 Settimo Milanese: via Bianchi'
                                  ' davanti alla farmacia Culzoni'
        }
        self.list = self.cities.keys()

